echo ....Pulling content from remote repo....
git pull
echo ....Staging all files....
git add .
git reset github_automator.sh
echo Enter message to add to commit: 
read msg
echo ....Committing all staged files to remote repo....
git commit -m "$msg"
echo ....Pushing commit to remote repo....
git push